name: anigav
channels:
  - defaults
dependencies:
  - pyopengl==3.1.1a1
  - pip:
    - adafruit-blinka>=6.13.0
    - adafruit-circuitpython-mcp3xxx>=1.4.5
    - pygame>=2.0.0
    - pyglm==1.1.7
    - pyopengl-accelerate>=3.1.5
    - pywavefront>=1.3.3
